### ISSUE TITLE
Hide Mouse Inside Window

### ISSUE THREAD

**Issue by gonutz** [x-hgg-x/arkanoid-go#2]
I find it irritating that I have the mouse cursor visible when it is inside the window. I think you want to hide it.

One thing I want to point out which is great is that you track the mouse position outside the window. This game would not be playable otherwise, so good job!

**Comment by x-hgg-x** [comment]
Fixed in https://github.com/x-hgg-x/arkanoid-go/commit/48c29e03e2d272512142c12410de634b4178cb99.

**Comment by x-hgg-x** [comment]
For your information you can change the controls by editing the file 
https://github.com/x-hgg-x/arkanoid-go/blob/master/config/controls.toml.
