### ISSUE TITLE
Horizontal Ball Movement

### ISSUE THREAD

**Issue by gonutz** [x-hgg-x/arkanoid-go#3]
I find that depending on how the ball bounces off blocks it flies nearly horizontally sometimes. This means it takes ages to come back down to the bottom. You should probably have some margin of vertical movement always. It seems to me that it would be possible that we have a perfectly horizontal ball that never does anything anymore after deleting its line of blocks. This might lead to an infinite game.

**Comment by x-hgg-x** [comment]
I have set a special action for this case : BallAttraction.
See https://github.com/x-hgg-x/arkanoid-go/blob/master/config/controls.toml to change controls.
