### ISSUE TITLE
Menu does not Always React to Keyboard

### ISSUE THREAD

**Issue by gonutz** [x-hgg-x/arkanoid-go#5]
In the main menu I can press UP/DOWN but only half of the time will this change the option. Are you not reacting to key events but instead rely on the key state during the frame?

**Comment by x-hgg-x** [comment]
Fixed in https://github.com/x-hgg-x/arkanoid-go/commit/25a746b3d824866c0e0850b9c150cdd59b41ff62.

The problem was if the mouse cursor was on a menu text, all keyboard events were ignored.
I have modified the menus so that the mouse events are handled only if the mouse is moved or clicked.
